import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { AppProvider } from "@/providers/app-provider";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Exam Hell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
